spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://foodiebuddy-rds.cva2ewm8ws16.ap-northeast-2.rds.amazonaws.com:3306/foodiebuddy?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

